provider: 
  name: faas
  gateway: 127.0.0.1:8080
  network: "func_functions"

functions:
  typetest:
    lang: dockerfile
    handler: ./
    image: my.private.registry.cluster.local
    secrets:
      - my-private-docker-registry-for-faas-netes
    environment:
        read_timeout: 120s
        write_timeout: 120s
